package defs

const (
	OptionHelp          = "help"
	OptionNoDownload    = "no-download"
	OptionNoUpload      = "no-upload"
	OptionNoICMP        = "no-icmp"
	OptionConcurrent    = "concurrent"
	OptionBytes         = "bytes"
	OptionMebiBytes     = "mebibytes"
	OptionSimple        = "simple"
	OptionCSV           = "csv"
	OptionCSVDelimiter  = "csv-delimiter"
	OptionCSVHeader     = "csv-header"
	OptionJSON          = "json"
	OptionList          = "list"
	OptionServer        = "server"
	OptionSource        = "source"
	OptionTimeout       = "timeout"
	OptionUploadSize    = "upload-size"
	OptionDuration      = "duration"
	OptionNoPreAllocate = "no-pre-allocate"
	OptionVersion       = "version"
	OptionDebug         = "debug"
)
