package defs

const (
	OptionHelp          = "help"
	OptionNoDownload    = "no-download"
	OptionNoUpload      = "no-upload"
	OptionNoICMP        = "no-icmp"
	OptionConcurrent    = "concurrent"
	OptionConcurrentAlt = "n"
	OptionBytes         = "bytes"
	OptionMebiBytes     = "mebibytes"
	OptionSimple        = "simple"
	OptionSimpleAlt     = "q"
	OptionCSV           = "csv"
	OptionCSVDelimiter  = "csv-delimiter"
	OptionCSVHeader     = "csv-header"
	OptionJSON          = "json"
	OptionList          = "list"
	OptionListAlt       = "l"
	OptionListProvinces = "list-prov"
	OptionServer        = "server"
	OptionServerAlt     = "s"
	OptionProvince      = "province"
	OptionProvinceAlt   = "p"
	OptionExclude       = "exclude"
	OptionSource        = "source"
	OptionTimeout       = "timeout"
	OptionUploadSize    = "upload-size"
	OptionDuration      = "duration"
	OptionDurationAlt   = "t"
	OptionNoPreAllocate = "no-pre-allocate"
	OptionVersion       = "version"
	OptionVersionAlt    = "v"
	OptionDebug         = "debug"
	OptionDisablePet    = "disable-exp"
	OptionDisablePetAlt = "E"
	OptionDisableTai    = "disable-nor"
	OptionDisableTaiAlt = "N"
)
