project_name: 'taierspeed-cli'
#dist: ./out
before:
  hooks:
    - go mod download
builds:
- main: ./main.go
  id: upx
  env:
  - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - -w -s -X "github.com/ztelliot/taierspeed-cli/defs.ProgName={{ .ProjectName }}" -X "github.com/ztelliot/taierspeed-cli/defs.ProgVersion=v{{ .Version }}" -X "github.com/ztelliot/taierspeed-cli/defs.BuildDate={{ .Date }}"
  goos:
    - linux
    - darwin
    - freebsd
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 7
  ignore:
    - goos: darwin
      goarch: arm64
  hooks:
    post: ./upx.sh -9 "{{ .Path }}"
- main: ./main.go
  id: no-upx
  env:
    - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - -w -s -X "github.com/ztelliot/taierspeed-cli/defs.ProgName={{ .ProjectName }}" -X "github.com/ztelliot/taierspeed-cli/defs.ProgVersion=v{{ .Version }}" -X "github.com/ztelliot/taierspeed-cli/defs.BuildDate={{ .Date }}"
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
    - mips
    - mipsle
    - mips64
    - mips64le
  gomips:
    - hardfloat
    - softfloat
  ignore:
    - goos: linux
      goarch: amd64
    - goos: linux
      goarch: arm64
    - goos: darwin
      goarch: amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
gitea_urls:
  api: "{{ .Env.GITEA_URL }}/api/v1"
  download: "{{ .Env.GITEA_URL }}"
release:
  gitea:
    owner: ztelliot
    name: taierspeed-cli
  disable: false

